//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualScripsMaker {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualScripsMaker.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00= 
        ///01=À
        ///02=Á
        ///03=Â
        ///04=Ç
        ///05=È
        ///06=É
        ///07=Ê
        ///08=Ë
        ///09=Ì
        ///0B=Î
        ///0C=Ï
        ///0D=Ò
        ///0E=Ó
        ///0F=Ô
        ///10=Œ
        ///11=Ù
        ///12=Ú
        ///13=Û
        ///14=Ñ
        ///15=ß
        ///16=à
        ///17=á
        ///19=ç
        ///1A=è
        ///1B=é
        ///1C=ê
        ///1D=ë
        ///1E=ì
        ///20=î
        ///21=ï
        ///22=ò
        ///23=ó
        ///24=ô
        ///25=œ
        ///26=ù
        ///27=ú
        ///28=û
        ///29=ñ
        ///2A=º
        ///2B=ª
        ///2D=&amp;
        ///2E=+
        ///34=[Lv]
        ///35==
        ///36=;
        ///51=¿
        ///52=¡
        ///53=[pk]
        ///54=[mn]
        ///55=[po]
        ///56=[ké]
        ///57=[bl]
        ///58=[oc]
        ///59=[k]
        ///5A=Í
        ///5B=%
        ///5C=(
        ///5D=)
        ///68=â
        ///6F=í
        ///79=[U]
        ///7A=[D]
        ///7B=[L]
        ///7C=[R]
        ///85=&lt;
        ///86=&gt;
        ///A1=0
        ///A2=1
        ///A3=2
        ///A4=3
        ///A5=4
        ///A6=5
        ///A7=6
        ///A8=7
        ///A9=8
        ///AA=9
        ///AB=!
        ///AC=?
        ///AD=.
        ///A [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HexEqualChar {
            get {
                return ResourceManager.GetString("HexEqualChar", resourceCulture);
            }
        }
    }
}
